import type { Label, Member, Project, Task } from "./types";

export const seedMembers: Member[] = [
  { id: "m-you", name: "You", initials: "YO", color: "#ff7a1a", isYou: true },
  { id: "m-marc", name: "Marc O.", initials: "MO", color: "#2f5bff" },
  { id: "m-lena", name: "Lena V.", initials: "LV", color: "#16b364" },
];

export const seedProjects: Project[] = [
  { id: "p-atlas", name: "Atlas Redesign", color: "#2f5bff" },
  { id: "p-mobile", name: "Mobile App", color: "#ff7a1a" },
  { id: "p-design", name: "Design System", color: "#16b364" },
  { id: "p-marketing", name: "Marketing Site", color: "#8a8a86" },
];

export const seedLabels: Label[] = [
  { id: "l-bug", name: "Bug", color: "#ff7a1a" },
  { id: "l-feature", name: "Feature", color: "#2f5bff" },
  { id: "l-research", name: "Research", color: "#6b6b66" },
  { id: "l-content", name: "Content", color: "#6b6b66" },
  { id: "l-mobile", name: "Mobile", color: "#6b6b66" },
  { id: "l-api", name: "API", color: "#6b6b66" },
  { id: "l-ideas", name: "Ideas", color: "#6b6b66" },
  { id: "l-shipped", name: "Shipped", color: "#16b364" },
];

export const seedTasks: Task[] = [
  {
    id: "t-1",
    projectId: "p-atlas",
    title: "Audit legacy icon set",
    status: "parked",
    priority: "P2",
    labelIds: ["l-research"],
    assigneeId: "m-marc",
    due: "2w",
    createdAt: "2026-09-01",
  },
  {
    id: "t-2",
    projectId: "p-atlas",
    title: "Explore dark-mode palette",
    status: "parked",
    priority: "P3",
    labelIds: ["l-ideas"],
    assigneeId: "m-you",
    due: "1w",
    createdAt: "2026-09-03",
  },
  {
    id: "t-3",
    projectId: "p-atlas",
    title: "Interview beta users",
    status: "parked",
    priority: "P3",
    labelIds: ["l-research"],
    assigneeId: "m-lena",
    due: "3d",
    createdAt: "2026-09-05",
  },
  {
    id: "t-4",
    projectId: "p-atlas",
    title: "Fix onboarding crash on iOS 17",
    description: "Repro: fresh install, skip sign-in, tap Get Started.",
    status: "todo",
    priority: "P1",
    labelIds: ["l-bug", "l-mobile"],
    assigneeId: "m-marc",
    due: "Today",
    createdAt: "2026-09-10",
  },
  {
    id: "t-5",
    projectId: "p-atlas",
    title: "Draft empty-state illustrations",
    status: "todo",
    priority: "P2",
    labelIds: ["l-feature"],
    assigneeId: "m-lena",
    due: "Mon",
    createdAt: "2026-09-11",
  },
  {
    id: "t-6",
    projectId: "p-atlas",
    title: "Write release notes v2.4",
    status: "todo",
    priority: "P2",
    labelIds: ["l-content"],
    assigneeId: "m-you",
    due: "Tue",
    createdAt: "2026-09-12",
  },
  {
    id: "t-7",
    projectId: "p-atlas",
    title: "Wire task-sync endpoint",
    description: "FastAPI service: POST /tasks, PATCH /tasks/:id/status.",
    status: "in_progress",
    priority: "P1",
    labelIds: ["l-feature", "l-api"],
    assigneeId: "m-marc",
    due: "In review",
    createdAt: "2026-09-08",
  },
  {
    id: "t-8",
    projectId: "p-atlas",
    title: "Build column drag & drop",
    status: "in_progress",
    priority: "P2",
    labelIds: ["l-feature"],
    assigneeId: "m-you",
    due: "60%",
    createdAt: "2026-09-09",
  },
  {
    id: "t-9",
    projectId: "p-atlas",
    title: "Set up project templates",
    status: "complete",
    priority: "P2",
    labelIds: ["l-shipped"],
    assigneeId: "m-lena",
    createdAt: "2026-08-28",
  },
  {
    id: "t-10",
    projectId: "p-atlas",
    title: "Define label color tokens",
    status: "complete",
    priority: "P3",
    labelIds: ["l-content"],
    assigneeId: "m-you",
    createdAt: "2026-08-25",
  },
  {
    id: "t-11",
    projectId: "p-mobile",
    title: "Push notification settings screen",
    status: "todo",
    priority: "P2",
    labelIds: ["l-feature", "l-mobile"],
    assigneeId: "m-you",
    createdAt: "2026-09-10",
  },
  {
    id: "t-12",
    projectId: "p-mobile",
    title: "App store screenshots",
    status: "parked",
    priority: "P4",
    labelIds: ["l-content"],
    assigneeId: null,
    createdAt: "2026-09-06",
  },
  {
    id: "t-13",
    projectId: "p-design",
    title: "Tokenize spacing scale",
    status: "in_progress",
    priority: "P2",
    labelIds: ["l-feature"],
    assigneeId: "m-lena",
    createdAt: "2026-09-07",
  },
  {
    id: "t-14",
    projectId: "p-marketing",
    title: "Landing page copy pass",
    status: "todo",
    priority: "P3",
    labelIds: ["l-content"],
    assigneeId: "m-you",
    createdAt: "2026-09-13",
  },
];
